Add parameter to specify the default return code on non-200 responses
phrawzty/check_http_json pull request #47
Opened 2021-01-06 12:15 UTC by JonasVerhofste

In case you always want critical when the response is unexpected (probably used in combination with `--status_level`)

2021-01-13 10:38 UTC, phrawzty commented
It seems like what you're really aiming at here is setting a default alert level for `--status_level`. That's not a bad idea but I wouldn't implement it this way; instead, why not something like `--status_level_defaut`?

2021-01-19 06:20 UTC, JonasVerhofste commented
@phrawzty Renamed :)

2021-01-25 11:37 UTC, phrawzty requested changes

2021-01-25 11:37 UTC, phrawzty commented on check_http_json.rb
> +        opts.on('--status_level_default INT', 'The default return code for not-expected http status codes. Defaults to 1.') do |x|
```suggestion
        opts.on('--status_level_default VALUE', 'The default return code for unexpected HTTP status codes. Defaults to 1.') do |x|
```

You'll also need to add this to the `Usage` section of the README. 😄

2021-01-25 12:04 UTC, merged

2021-01-25 12:16 UTC, phrawzty commented
Thanks for the PR! :)

2021-01-25 12:25 UTC, JonasVerhofste commented
Thanks for the reviews! :)